-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 16:21:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Page` (
  `url` VARCHAR(511) NOT NULL,
  `last_title` VARCHAR(255) NULL,
  `last_img` VARCHAR(511) NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subscription` (
  `user_id` VARCHAR(511) NOT NULL,
  `page_url` VARCHAR(511) NOT NULL,
  `rank` INT NULL,
  `has_new` TINYINT NULL,
  PRIMARY KEY (`user_id`, `page_url`),
  INDEX `fk_User_has_Page_Page1_idx` (`page_url` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Page_Page1`
    FOREIGN KEY (`page_url`)
    REFERENCES `mydb`.`Page` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
